title: "KOICA"
description: KOICA-UPLB-IRRI Project
theme: jekyll-theme-cayman
 
# Add custom CSS
plugins:
  - jekyll-include-cache
 
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: "/assets/style.css"
